rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1

gemfile:
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile