language: ruby

sudo: false
cache: bundler

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

before_install:
  - gem update --system 2.7.8
  - gem install bundler -v 1.17.3

gemfile:
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/4.1.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/4.2.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/5.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/5.1.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/5.2.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/6.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.2.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/5.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/5.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/5.2.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/6.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/5.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/5.2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/5.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/5.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/5.1.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/5.2.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/3.1.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/3.1.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/3.1.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/3.1.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/4.2.gemfile
